### ISSUE TITLE
LDES members replication fail to http client sink

### ISSUE THREAD

**Issue by zargha** [Informatievlaanderen/VSDS-LDESClient-NifiProcessor#40]
### The Problem
The problem occurred while testing the e2e demo for sprint 2. After uploading the `alfa.json.ld`, `beta.json.ld` and `gamma.json.ld` fragments which results in total amount of 501 members, and after starting the NiFi workflow only 500 members are replicated. The last fragment and its member doesnt replicated to the client sink.

### Environment
**Components under test**
- vsds/ldes-server-simulator
- vsds/ldes-client-sink
- vsds/ldes-client-workflow
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20
```
```
$ docker --version
Docker version 20.10.17, build 100c701
$ docker-compose --version
docker-compose version 1.29.2, build 5becea4c

Google Chrome
Version 102.0.5005.115 (Official Build) (64-bit)
```
### Error logs
[logs.txt](https://github.com/Informatievlaanderen/VSDS-LDESClient-NifiProcessor/files/8926933/logs.txt)

### Steps to reproduce
1. Start you system as described [here]( https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/20220607.demo-1#start-systems)
2. Setup the demo as described [here](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/20220607.demo-1#setup-demo)
3. Start the replication as described [here](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/20220607.demo-1#replicate)
4. When replication starts, during the process send continuous `GET/` requests to ldes client sink at `http://localhost:9003`

During step 4 the problem occurred.

**Comment by Krieke** [comment]
@zargha 

- Please don't use gist.github.com to share your log files.  You can easily attach files by dragging & dropping, selecting or pasting them. 
- add the Cegeka developers as Assignees

**Comment by Yalz** [comment]
Has this been tested with the june demo ?

**Comment by zargha** [comment]
> Has this been tested with the june demo ?

Yes!

**Comment by zargha** [comment]
Yes

**Comment by Yalz** [comment]
Hi @zargha ,
I tried these steps myself once more and I can clearly see 501 member in the sink. (+ inside Nifi workflow)
Could you perhaps retry?

**Comment by zargha** [comment]
> Hi @zargha , I tried these steps myself once more and I can clearly see 501 member in the sink. (+ inside Nifi workflow) Could you perhaps retry?

Hi @Yalz so the problem still persists unfortunately! 

`ldes-client-sink_1       | GET /
ldes-server-simulator_1  | GET /api/v1/ldes/mobility-hindrances?generatedAtTime=2022-06-03T07:58:29.2Z
ldes-client-sink_1       | GET /
ldes-client-sink_1       | GET /
ldes-server-simulator_1  | GET /api/v1/ldes/mobility-hindrances?generatedAtTime=2022-06-03T07:58:29.2Z
ldes-client-workflow_1   | 2022-07-04 09:02:55,227 INFO [Cleanup Archive for default] o.a.n.c.repository.FileSystemRepository Successfully deleted 0 files (0 bytes) from archive
ldes-client-workflow_1   | 2022-07-04 09:02:57,507 INFO [pool-7-thread-1] o.a.n.c.r.WriteAheadFlowFileRepository Initiating checkpoint of FlowFile Repository
ldes-client-workflow_1   | 2022-07-04 09:02:57,507 INFO [pool-7-thread-1] o.a.n.c.r.WriteAheadFlowFileRepository Successfully checkpointed FlowFile Repository with 0 records in 0 milliseconds
ldes-server-simulator_1  | GET /api/v1/ldes/mobility-hindrances?generatedAtTime=2022-06-03T07:58:29.2Z
ldes-client-sink_1       | GET /
ldes-server-simulator_1  | GET /api/v1/ldes/mobility-hindrances?generatedAtTime=2022-06-03T07:58:29.2Z
ldes-client-workflow_1   | 2022-07-04 09:03:17,507 INFO [pool-7-thread-1] o.a.n.c.r.WriteAheadFlowFileRepository Initiating checkpoint of FlowFile Repository
ldes-client-workflow_1   | 2022-07-04 09:03:17,508 INFO [pool-7-thread-1] o.a.n.c.r.WriteAheadFlowFileRepository Successfully checkpointed FlowFile Repository with 0 records in 0 milliseconds
ldes-server-simulator_1  | GET /api/v1/ldes/mobility-hindrances?generatedAtTime=2022-06-03T07:58:29.2Z
ldes-server-simulator_1  | GET /
ldes-server-simulator_1  | GET /api/v1/ldes/mobility-hindrances?generatedAtTime=2022-06-03T07:58:29.2Z
ldes-client-workflow_1   | 2022-07-04 09:03:37,508 INFO [pool-7-thread-1] o.a.n.c.r.WriteAheadFlowFileRepository Initiating checkpoint of FlowFile Repository
ldes-client-workflow_1   | 2022-07-04 09:03:37,508 INFO [pool-7-thread-1] o.a.n.c.r.WriteAheadFlowFileRepository Successfully checkpointed FlowFile Repository with 0 records in 0 milliseconds
`
i can see from the logs that the client send the GET /api/v1/ldes/mobility-hindrances?generatedAtTime=2022-06-03T07:58:29.2Z  request but the count is stuck at 500!

**Comment by zargha** [comment]
the issue occurs on the `main` branch as well. See logs:
[logs_04072022_main.txt](https://github.com/Informatievlaanderen/VSDS-LDESClient-NifiProcessor/files/9038359/logs_04072022_main.txt)

**Comment by zargha** [comment]
The replication has failed for e2e-test 20220524.demo-1 as well on this git tag `06f4ca08a7fbedfc57cf6fc03c34ab02a8623ee6`

**Comment by rorlic** [comment]
When I look into your [logs.txt](https://github.com/Informatievlaanderen/VSDS-LDESClient-NifiProcessor/files/8926933/logs.txt) file, I can see:

```
ldes-client-workflow_1   | 2022-07-04 09:46:22,996 ERROR [Timer-Driven Process Thread-5] o.a.nifi.processors.standard.InvokeHTTP InvokeHTTP[id=1197809b-910c-3ebb-3bbe-c1f14f1cbfdc] Routing to Failure due to exception: org.apache.nifi.processor.exception.ProcessException: IOException thrown from InvokeHTTP[id=1197809b-910c-3ebb-3bbe-c1f14f1cbfdc]: java.net.SocketException: Broken pipe: org.apache.nifi.processor.exception.ProcessException: IOException thrown from InvokeHTTP[id=1197809b-910c-3ebb-3bbe-c1f14f1cbfdc]: java.net.SocketException: Broken pipe
ldes-client-workflow_1   | - Caused by: java.net.SocketException: Broken pipe
ldes-client-workflow_1   | org.apache.nifi.processor.exception.ProcessException: IOException thrown from InvokeHTTP[id=1197809b-910c-3ebb-3bbe-c1f14f1cbfdc]: java.net.SocketException: Broken pipe
ldes-client-workflow_1   |      at org.apache.nifi.controller.repository.StandardProcessSession.exportTo(StandardProcessSession.java:3651)
ldes-client-workflow_1   |      at org.apache.nifi.processors.standard.InvokeHTTP$1.writeTo(InvokeHTTP.java:1153)
```

Notice the processor that is causing the error: `o.a.nifi.processors.standard.InvokeHTTP` and the error itself `java.net.SocketException: Broken pipe`. To me that sounds like a (docker) network glitch. Now, also note the action taken by NiFi: `Routing to Failure due to exception`. This is due to the way the workflow is configured. You can see this in the workflow: double-click the `InvokeHTTP processor` and select the `Relations` tab. Note that on `Failure` NiFi will `Terminate`. The other option is `Retry`, which would obviously have been better in this case.

This most likely also explains why Jan could not reproduce it.

In your [logs_04072022_main.txt](https://github.com/Informatievlaanderen/VSDS-LDESClient-NifiProcessor/files/9038359/logs_04072022_main.txt) file I see the same error.

**Comment by WLefever-Cegeka** [comment]
@zargha , I created a PR which should allow you to rerun the demos. The issue is not related to the Client, but to Nifi. Added a retry mechanism. Can you check this PR: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/pull/29
And if okay, comment on this issue and close :-)
