### ISSUE TITLE
ldes-client-nifiprocessor fails to start up

### ISSUE THREAD

**Issue by zargha** [Informatievlaanderen/VSDS-LDESClient-NifiProcessor#86]
### The Problem
While testing out the e2e gipod test https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/main/e2e-test/use-cases/gipod/3.synchronize-ldes, the `simulator-workflow-sink/nifi-workflow` fails to start up

### Environment
**Components under test**
- vsds/ldes-server-simulator
- vsds/ldes-client-sink
- vsds/ldes-client-workflow
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20
```
```
$ docker --version
Docker version 20.10.17, build 100c701
$ docker compose version
Docker Compose version v2.6.0
```
```
LDES_CLIENT_NAR_TAG=20220704.153332-11
The GitHub commit tag: https://github.com/Informatievlaanderen/VSDS-LDESClient-NifiProcessor/commit/b1a77f5d8496e76dedb09a7105c564faab78eb63

```
### Error logs
```
nifi-workflow          |                org.apache.nifi:nifi-framework-nar:1.16.3 || ./work/nar/framework/nifi-framework-nar-1.16.3.nar-unpacked
nifi-workflow          |        org.apache.nifi.ldap.tenants.LdapUserGroupProvider
nifi-workflow          |                org.apache.nifi:nifi-ldap-iaa-providers-nar:1.16.3 || ./work/nar/extensions/nifi-ldap-iaa-providers-nar-1.16.3.nar-unpacked
nifi-workflow          |        === End UserGroupProvider types ===
nifi-workflow          |        === StatusHistoryRepository Type ===
nifi-workflow          |        org.apache.nifi.controller.status.history.EmbeddedQuestDbStatusHistoryRepository
nifi-workflow          |                org.apache.nifi:nifi-framework-nar:1.16.3 || ./work/nar/framework/nifi-framework-nar-1.16.3.nar-unpacked
nifi-workflow          |        org.apache.nifi.controller.status.history.VolatileComponentStatusRepository
nifi-workflow          |                org.apache.nifi:nifi-framework-nar:1.16.3 || ./work/nar/framework/nifi-framework-nar-1.16.3.nar-unpacked
nifi-workflow          |        === End StatusHistoryRepository types ===
nifi-workflow          |        === NarProvider Type ===
nifi-workflow          |        org.apache.nifi.nar.hadoop.HDFSNarProvider
nifi-workflow          |                org.apache.nifi:nifi-hadoop-nar:1.16.3 || ./work/nar/extensions/nifi-hadoop-nar-1.16.3.nar-unpacked
nifi-workflow          |        org.apache.nifi.registry.extension.NiFiRegistryNarProvider
nifi-workflow          |                org.apache.nifi:nifi-framework-nar:1.16.3 || ./work/nar/framework/nifi-framework-nar-1.16.3.nar-unpacked
nifi-workflow          |        === End NarProvider types ===
nifi-workflow          |        === StateProvider Type ===
nifi-workflow          |        org.apache.nifi.controller.state.providers.local.WriteAheadLocalStateProvider
nifi-workflow          |                org.apache.nifi:nifi-framework-nar:1.16.3 || ./work/nar/framework/nifi-framework-nar-1.16.3.nar-unpacked
nifi-workflow          |        org.apache.nifi.controller.state.providers.zookeeper.ZooKeeperStateProvider
nifi-workflow          |                org.apache.nifi:nifi-framework-nar:1.16.3 || ./work/nar/framework/nifi-framework-nar-1.16.3.nar-unpacked
nifi-workflow          |        org.apache.nifi.redis.state.RedisStateProvider
nifi-workflow          |                org.apache.nifi:nifi-redis-nar:1.16.3 || ./work/nar/extensions/nifi-redis-nar-1.16.3.nar-unpacked
nifi-workflow          |        === End StateProvider types ===
nifi-workflow          | 2022-08-22 12:51:33,079 WARN [main] org.apache.nifi.web.server.JettyServer Failed to start web server... shutting down.
nifi-workflow          | java.lang.NullPointerException: Cannot invoke "org.apache.nifi.nar.ExtensionMapping.size()" because "extensionMapping" is null
nifi-workflow          |        at org.apache.nifi.documentation.DocGenerator.generate(DocGenerator.java:63)
nifi-workflow          |        at org.apache.nifi.web.server.JettyServer.start(JettyServer.java:1005)
nifi-workflow          |        at org.apache.nifi.NiFi.<init>(NiFi.java:170)
nifi-workflow          |        at org.apache.nifi.NiFi.<init>(NiFi.java:82)
nifi-workflow          |        at org.apache.nifi.NiFi.main(NiFi.java:330)
nifi-workflow exited with code 0
```
### Steps to reproduce
1. Start you system as described [here](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/main/e2e-test/use-cases/gipod/3.synchronize-ldes/README.md#test-setup)

During `docker compose up` the problem occurs.

**Comment by Yalz** [comment]
@rorlic this is the same problem I had on friday. For me the issue was fixed with both :

- moving the SINGLE_USER_CREDENTIALS_USERNAME and SINGLE_USER_CREDENTIALS_PASSWORD args to "environment" in the docker compose 
- updating my personal access token

@zargha what value do you use for PAT_READ_PACKAGES ? is this your own PAT ? if not, please update that one with an up to date value.

**Comment by rorlic** [comment]
Most likely cause is that the NAR file was not correctly dowloaded while creating the docker image. There are two possible causes: permissions (eg. PAT expired) or file not found (eg. NAR files moved). The 'nar' file in the docker image contains the actual error text.

**Comment by zargha** [comment]
The issue has been tested with `LDES_CLIENT_NAR_TAG=20220704.153332-11` and `build.ARTIFACT_ID: ldes-processors` in `VSDS-LDES-E2E-testing/e2e-test/support/context/simulator-workflow-sink-mongo/docker-compose.yml` file.
